// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Models;

public partial class Customer
{
    public int CustomerID { get; set; }

    public int? UserID { get; set; }

    public int ContactID { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual ContactInfo Contact { get; set; }

    public virtual ICollection<Loyalty> Loyalties { get; set; } = new List<Loyalty>();

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();

    public virtual User User { get; set; }
}