// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Models;

public partial class Discount
{
    public int DiscountID { get; set; }

    public string DiscountDescription { get; set; }

    public int ProductID { get; set; }

    public string DiscountCode { get; set; }

    public int DiscountTypeID { get; set; }

    public decimal DiscountValue { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual Object DiscountType { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<SaleItem> SaleItems { get; set; } = new List<SaleItem>();

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();
}