// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Models;

public partial class Employee
{
    public int EmployeeID { get; set; }

    public int? UserID { get; set; }

    public int BranchID { get; set; }

    public int ContactID { get; set; }

    public int PositionID { get; set; }

    public int DepartmentID { get; set; }

    public DateOnly? HireDate { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ContactInfo Contact { get; set; }

    public virtual Object Department { get; set; }

    public virtual Object Position { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();

    public virtual User User { get; set; }
}