// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Models;

public partial class Loyalty
{
    public int LoyaltyID { get; set; }

    public int CustomerID { get; set; }

    public int LoyaltyProgID { get; set; }

    public int PointsEarned { get; set; }

    public int MembershipLevelID { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual LoyaltyProg LoyaltyProg { get; set; }

    public virtual Object MembershipLevel { get; set; }
}