// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Models;

public partial class Loyalty
{
    public int LoyaltyId { get; set; }

    public int CustomerId { get; set; }

    public int LoyaltyProgId { get; set; }

    public int PointsEarned { get; set; }

    public int MembershipLevelId { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual LoyaltyProg LoyaltyProg { get; set; }

    public virtual Object MembershipLevel { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}