// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Models;

public partial class LoyaltyProg
{
    public int LoyaltyProgId { get; set; }

    public string LoyaltyProgName { get; set; }

    public string LoyaltyProgDescription { get; set; }

    public decimal PointsPerAmount { get; set; }

    public decimal? PointsMultiplier { get; set; }

    public DateOnly? Validity { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<Loyalty> Loyalties { get; set; } = new List<Loyalty>();

    public virtual User UpdatedByNavigation { get; set; }
}