// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int SaleId { get; set; }

    public decimal PaymentAmount { get; set; }

    public int PaymentCurrencyId { get; set; }

    public DateOnly PaymentDate { get; set; }

    public TimeOnly PaymentTime { get; set; }

    public int PaymentTypeId { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Object PaymentCurrency { get; set; }

    public virtual Object PaymentType { get; set; }

    public virtual Sale Sale { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}