// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Models;

public partial class ProductCategory
{
    public int ProductCategoryId { get; set; }

    public int ProductId { get; set; }

    public int CategoryId { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual Category Category { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Product Product { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}