// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Models;

public partial class ProductItem
{
    public int ProductItemId { get; set; }

    public int ProductId { get; set; }

    public int BranchId { get; set; }

    public string SerialNumber { get; set; }

    public DateTime? ExpirationDate { get; set; }

    public string BatchNumber { get; set; }

    public int StatusId { get; set; }

    public DateTime? PurchaseDate { get; set; }

    public DateTime? SaleDate { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<SaleItem> SaleItems { get; set; } = new List<SaleItem>();

    public virtual Object Status { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}