// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Models;

public partial class SaleItem
{
    public int SaleItemId { get; set; }

    public int SaleId { get; set; }

    public int ProductId { get; set; }

    public int? ProductItemId { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal TotalPrice { get; set; }

    public int? TaxId { get; set; }

    public decimal? TaxAmount { get; set; }

    public int? DiscountId { get; set; }

    public decimal? DiscountAmount { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Discount Discount { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductItem ProductItem { get; set; }

    public virtual Sale Sale { get; set; }

    public virtual Taxis Tax { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}