// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Models;

public partial class Sale
{
    public int SaleId { get; set; }

    public int StoreId { get; set; }

    public int? CustomerId { get; set; }

    public int EmployeeId { get; set; }

    public DateOnly SaleDate { get; set; }

    public TimeOnly SaleTime { get; set; }

    public int SaleCurrencyId { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal NetAmount { get; set; }

    public int ItemCount { get; set; }

    public string ReceiptNumber { get; set; }

    public int StatusId { get; set; }

    public int? TaxId { get; set; }

    public decimal? TaxAmount { get; set; }

    public int? DiscountId { get; set; }

    public decimal? DiscountAmount { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Discount Discount { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Object SaleCurrency { get; set; }

    public virtual ICollection<SaleItem> SaleItems { get; set; } = new List<SaleItem>();

    public virtual Object Status { get; set; }

    public virtual Branch Store { get; set; }

    public virtual Taxis Tax { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}