// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Models;

public partial class Supplier
{
    public int SupplierID { get; set; }

    public string SupplierName { get; set; }

    public int? ContactID { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual ContactInfo Contact { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}