// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Models;

public partial class Taxis
{
    public int TaxId { get; set; }

    public byte[] TaxName { get; set; }

    public decimal TaxRate { get; set; }

    public int TaxTypeId { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<SaleItem> SaleItems { get; set; } = new List<SaleItem>();

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();

    public virtual Object TaxType { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}