// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TPOS.Core.Models;
using System;
using System.Collections.Generic;

namespace TPOS.Infrastructure.Configurations
{
    public partial class LoyaltyConfiguration : IEntityTypeConfiguration<Loyalty>
    {
        public void Configure(EntityTypeBuilder<Loyalty> entity)
        {
            entity.Property(e => e.LoyaltyId).HasColumnName("LoyaltyID");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.LoyaltyProgId).HasColumnName("LoyaltyProgID");
            entity.Property(e => e.MembershipLevelId).HasColumnName("MembershipLevelID");
            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.LoyaltyCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Loyalties_Users1");

            entity.HasOne(d => d.Customer).WithMany(p => p.Loyalties)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Loyalties_Customers");

            entity.HasOne(d => d.LoyaltyProg).WithMany(p => p.Loyalties)
                .HasForeignKey(d => d.LoyaltyProgId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Loyalties_LoyaltyProgs");

            entity.HasOne(d => d.MembershipLevel).WithMany(p => p.Loyalties)
                .HasForeignKey(d => d.MembershipLevelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Loyalties_Objects");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.LoyaltyUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Loyalties_Users2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Loyalty> entity);
    }
}
