// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TPOS.Core.Entities.Generated;
using TPOS.Infrastructure;

namespace TPOS.Infrastructure.Configurations
{
    public partial class LoyaltyConfiguration : IEntityTypeConfiguration<Loyalty>
    {
        public void Configure(EntityTypeBuilder<Loyalty> entity)
        {
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");

                entity.Property(e => e.PointsEarned).HasDefaultValue(0);

                entity.Property(e => e.UpdatedOn).HasColumnType("datetime");

                entity.HasOne(d => d.Customer)
                    .WithMany(p => p.Loyalties)
                    .HasForeignKey(d => d.CustomerID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Loyalties_Customers");

                entity.HasOne(d => d.LoyaltyProg)
                    .WithMany(p => p.Loyalties)
                    .HasForeignKey(d => d.LoyaltyProgID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Loyalties_LoyaltyProgs");

                entity.HasOne(d => d.MembershipLevel)
                    .WithMany(p => p.Loyalties)
                    .HasForeignKey(d => d.MembershipLevelID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Loyalties_Objects");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Loyalty> entity);
    }
}
