// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TPOS.Core.Models;
using System;
using System.Collections.Generic;
using Object = TPOS.Core.Models.Object;

namespace TPOS.Infrastructure.Configurations
{
    public partial class ObjectConfiguration : IEntityTypeConfiguration<Object>
    {
        public void Configure(EntityTypeBuilder<Object> entity)
        {
            entity.HasKey(e => e.ObjId);

            entity.Property(e => e.ObjId).HasColumnName("ObjID");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ObjDesc).HasColumnType("text");
            entity.Property(e => e.ObjKey)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.ObjText1).IsUnicode(false);
            entity.Property(e => e.ObjText2).IsUnicode(false);
            entity.Property(e => e.ObjText3).IsUnicode(false);
            entity.Property(e => e.ObjType)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.ObjectCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Objects_Users1");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.ObjectUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Objects_Users2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Object> entity);
    }
}
