// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TPOS.Core.Entities;
using TPOS.Infrastructure;

namespace TPOS.Infrastructure.Configurations
{
    public partial class TaxConfiguration : IEntityTypeConfiguration<Tax>
    {
        public void Configure(EntityTypeBuilder<Tax> entity)
        {
            entity.HasKey(e => e.TaxID);

            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.TaxName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TaxRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");

            entity.HasOne(d => d.TaxType).WithMany(p => p.Taxes)
                .HasForeignKey(d => d.TaxTypeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Taxes_Objects");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tax> entity);
    }
}
