// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TPOS.Core.Models;
using System;
using System.Collections.Generic;

namespace TPOS.Infrastructure.Configurations
{
    public partial class TaxisConfiguration : IEntityTypeConfiguration<Taxis>
    {
        public void Configure(EntityTypeBuilder<Taxis> entity)
        {
            entity.HasKey(e => e.TaxId);

            entity.Property(e => e.TaxId).HasColumnName("TaxID");
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.TaxName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TaxRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.TaxTypeId).HasColumnName("TaxTypeID");
            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.TaxisCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Taxes_Users1");

            entity.HasOne(d => d.TaxType).WithMany(p => p.Taxes)
                .HasForeignKey(d => d.TaxTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Taxes_Objects");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.TaxisUpdatedByNavigations)
                .HasForeignKey(d => d.UpdatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Taxes_Users2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Taxis> entity);
    }
}
