// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System.Collections.Generic;
using TPOS.Core.Entities.Generated;
using Object = TPOS.Core.Entities.Generated.Object;

namespace TPOS.Core.Interfaces.Repositories
{
    public interface IObjectRepository : IRepository<Object>
    {
        //Add any additional specific methods other than the generic ones
    }
}
