// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System.Collections.Generic;
using TPOS.Core.Entities.Generated;

namespace TPOS.Core.Interfaces.Repositories
{
    public interface ITaxRepository : IRepository<Tax>
    {
        //Add any additional specific methods other than the generic ones
    }
}
