// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System.Collections.Generic;
using TPOS.Domain.Entities.Generated;

namespace TPOS.Application.Interfaces.Repositories
{
    public interface IContactInfoRepository : IRepository<ContactInfo>
    {
        //Add any additional specific methods other than the generic ones
    }
}
