// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using TPOS.Application.Interfaces.Repositories;

namespace TPOS.Application.Interfaces
{
    public interface IUnitOfWork : IDisposable
    {
        IProductCategoryRepository ProductCategoryRepository { get; }
        ICustomerRepository CustomerRepository { get; }
        IProductItemRepository ProductItemRepository { get; }
        IDiscountRepository DiscountRepository { get; }
        IPaymentRepository PaymentRepository { get; }
        ISaleRepository SaleRepository { get; }
        ICurrencyRateRepository CurrencyRateRepository { get; }
        IObjectRepository ObjectRepository { get; }
        IEmployeeRepository EmployeeRepository { get; }
        ISaleItemRepository SaleItemRepository { get; }
        IFolderRepository FolderRepository { get; }
        ILoyaltyRepository LoyaltyRepository { get; }
        ICompanyRepository CompanyRepository { get; }
        IBranchRepository BranchRepository { get; }
        IUserRepository UserRepository { get; }
        ITaxRepository TaxRepository { get; }
        ILoyaltyProgRepository LoyaltyProgRepository { get; }
        IContactInfoRepository ContactInfoRepository { get; }
        IProductRepository ProductRepository { get; }
        IRoleRepository RoleRepository { get; }
        IUserRoleRepository UserRoleRepository { get; }
        IInventoryRepository InventoryRepository { get; }
        ICategoryRepository CategoryRepository { get; }
        IFileServerRepository FileServerRepository { get; }
        ISupplierRepository SupplierRepository { get; }
        IRolePermissionRepository RolePermissionRepository { get; }
        IMenuRepository MenuRepository { get; }
        IPermissionRepository PermissionRepository { get; }

        Task<int> CompleteAsync();
    }
}
