// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using TPOS.Application.Interfaces.Repositories;
using TPOS.Domain.Entities.Generated;

namespace TPOS.Infrastructure.Data.Repositories
{
    public class UserRepository : Repository<User>, IUserRepository
    {
        public UserRepository(AppDbContext context) : base(context)
        {
        }

        //Override any generic method for your own custom implemention, and implement specific repository methods of the IUserRepository.cs

        public bool HasPermission(int userID, string permission)
        {
            var userRoleIDs = _context.UserRoles
                .Where(ur => ur.UserID == userID)
                .Select(ur => ur.RoleID)
                .ToList();

            if (!userRoleIDs.Any())
            {
                return false;
            }

            var hasPermission = _context.RolePermissions
                .Include(rp => rp.Permission)
                .Where(rp => userRoleIDs.Contains(rp.RoleID) && rp.Permission.Value.ToLower().Equals(permission.ToLower()))
                .Any();

            return hasPermission;
        }

    }
}
