// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TPOS.Domain.Entities.Generated;
using TPOS.Infrastructure.Data;

namespace TPOS.Infrastructure.Data.Configurations
{
    public partial class MenuConfiguration : IEntityTypeConfiguration<Menu>
    {
        public void Configure(EntityTypeBuilder<Menu> entity)
        {
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.IconColor)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.MenuBadge)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.MenuDescription)
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.MenuIcon)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.MenuName)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.RouteUrl)
                .HasMaxLength(256)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Permission).WithMany(p => p.Menus)
                .HasForeignKey(d => d.PermissionID)
                .HasConstraintName("FK_Menus_Permissions");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Menu> entity);
    }
}
