// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TPOS.Core.Entities.Generated;
using TPOS.Infrastructure.Data;
using Object = TPOS.Core.Entities.Generated.Object;

namespace TPOS.Infrastructure.Data.Configurations
{
    public partial class ObjectConfiguration : IEntityTypeConfiguration<Object>
    {
        public void Configure(EntityTypeBuilder<Object> entity)
        {
            entity.HasKey(e => e.ObjID);

            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.ObjDesc).HasColumnType("text");
            entity.Property(e => e.ObjKey)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.ObjText1).IsUnicode(false);
            entity.Property(e => e.ObjText2).IsUnicode(false);
            entity.Property(e => e.ObjText3).IsUnicode(false);
            entity.Property(e => e.ObjType)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Object> entity);
    }
}
