// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Entities;

public partial class CurrencyRate
{
    public int CurrencyRateID { get; set; }

    public int BaseCurrencyID { get; set; }

    public int ForeignCurrencyID { get; set; }

    public decimal Rate { get; set; }

    public DateOnly FromDate { get; set; }

    public DateOnly ToDate { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual Object BaseCurrency { get; set; }

    public virtual Object ForeignCurrency { get; set; }
}