// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Entities;

public partial class Object
{
    public int ObjID { get; set; }

    public string ObjType { get; set; }

    public string ObjKey { get; set; }

    public string ObjDesc { get; set; }

    public string ObjText1 { get; set; }

    public string ObjText2 { get; set; }

    public string ObjText3 { get; set; }

    public bool IsSysObj { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<CurrencyRate> CurrencyRateBaseCurrencies { get; set; } = new List<CurrencyRate>();

    public virtual ICollection<CurrencyRate> CurrencyRateForeignCurrencies { get; set; } = new List<CurrencyRate>();

    public virtual ICollection<Discount> Discounts { get; set; } = new List<Discount>();

    public virtual ICollection<Employee> EmployeeDepartments { get; set; } = new List<Employee>();

    public virtual ICollection<Employee> EmployeePositions { get; set; } = new List<Employee>();

    public virtual ICollection<Loyalty> Loyalties { get; set; } = new List<Loyalty>();

    public virtual ICollection<Payment> PaymentPaymentCurrencies { get; set; } = new List<Payment>();

    public virtual ICollection<Payment> PaymentPaymentTypes { get; set; } = new List<Payment>();

    public virtual ICollection<ProductItem> ProductItems { get; set; } = new List<ProductItem>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<Sale> SaleSaleCurrencies { get; set; } = new List<Sale>();

    public virtual ICollection<Sale> SaleStatuses { get; set; } = new List<Sale>();

    public virtual ICollection<Tax> Taxes { get; set; } = new List<Tax>();
}