// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Entities;

public partial class Sale
{
    public int SaleID { get; set; }

    public int BranchID { get; set; }

    public int? CustomerID { get; set; }

    public int EmployeeID { get; set; }

    public DateOnly SaleDate { get; set; }

    public TimeOnly SaleTime { get; set; }

    public int SaleCurrencyID { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal NetAmount { get; set; }

    public int ItemCount { get; set; }

    public string ReceiptNumber { get; set; }

    public int StatusID { get; set; }

    public int? TaxID { get; set; }

    public decimal? TaxAmount { get; set; }

    public int? DiscountID { get; set; }

    public decimal? DiscountAmount { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Discount Discount { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Object SaleCurrency { get; set; }

    public virtual ICollection<SaleItem> SaleItems { get; set; } = new List<SaleItem>();

    public virtual Object Status { get; set; }

    public virtual Tax Tax { get; set; }
}