// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Entities;

public partial class SaleItem
{
    public int SaleItemID { get; set; }

    public int SaleID { get; set; }

    public int ProductID { get; set; }

    public int? ProductItemID { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal TotalPrice { get; set; }

    public int? TaxID { get; set; }

    public decimal? TaxAmount { get; set; }

    public int? DiscountID { get; set; }

    public decimal? DiscountAmount { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual Discount Discount { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductItem ProductItem { get; set; }

    public virtual Sale Sale { get; set; }

    public virtual Tax Tax { get; set; }
}