// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TPOS.Core.Entities;

public partial class Tax
{
    public int TaxID { get; set; }

    public string TaxName { get; set; }

    public decimal TaxRate { get; set; }

    public int TaxTypeID { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<SaleItem> SaleItems { get; set; } = new List<SaleItem>();

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();

    public virtual Object TaxType { get; set; }
}